### ISSUE TITLE
Stock symbol?

### ISSUE THREAD

**Issue by jamesliu1** [DavidCico/Forecasting-direction-of-trade-an-example-with-LSTM-neural-network#1]
Thanks for sharing your research. 
To replicate the results, 
could you tell me which stock symbol was used in the training data back in 2017?

**Comment by DavidCico** [comment]
Hi James,
actually I have no idea from which ticker the data is coming from. I basically got this data and project for an interview. I don't have myself access to any tick data. Hope you understand, thanks.

**Comment by jamesliu1** [comment]
I see, thank you for updating the repo. It's very helpful.
